#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i '$ a\\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1177-web-01 54.146.199.106:80\n\tserver 1177-web-02 18.212.79.62:80' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
